name: first workflow
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print a welcome message
        run: echo "welcome message"
      - name : checkout code
        uses: actions/checkout@v6.0.3
      - name: list a repos
        run: ls -la
